name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
env:
  IMAGE_NAME: charlotte

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
